FROM node:18-alpine as build
WORKDIR /app

ARG SENTRY_AUTH_TOKEN
ARG REACT_APP_MEDIA_BASE_URL
ARG REACT_APP_CMS_URL
ARG REACT_APP_PMS_URL
ARG REACT_APP_WMS_URL
ARG REACT_APP_IMS_URL
ARG REACT_APP_FILMBAZI_API_URL
ARG REACT_APP_BANK_URL
ARG REACT_APP_ASHBARIA_API_URL
ARG REACT_APP_SENTRY_DNS
ARG REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID
ARG REACT_APP_GTM_ID
ARG REACT_APP_CLARITY_TOKEN
ARG REACT_APP_GOFTINO_TOKEN
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_APPLICATION_ID
ARG REACT_APP_JAVASCRIPT_KEY
ARG REACT_APP_METABASE_SITE_URL
ARG REACT_APP_METABASE_SECRET_KEY


COPY ./package.json ./
RUN yarn
ENV PATH="./node_modules/.bin:$PATH"
COPY . .
RUN yarn build

# Stage 2: Serve with default nginx config
FROM nginx:alpine AS production

# Copy built assets to nginx's default html directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 and run nginx in foreground
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]